####

In [147]:
import pandas as pd

df_madrid = pd.read_csv('Datos.csv')

## DF_MADRID

### Exploración inicial

In [148]:
def explorar_df(df):
    print(df.info())

    print('Primeras filas')
    print(df.head())

    print('Describe()')
    print(df.describe(include='all').T)

    print('Nulos')
    nulos = df.isnull().sum()
    print(nulos[nulos > 0] if nulos.any() else 'Notnnull')

    print('Duplicados')
    print(df.duplicated().sum())
    
    print('Tamaño')
    print(f"Filas: {df.shape[0]} | Columnas: {df.shape[1]}")

In [149]:
explorar_df(df_madrid)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11826 entries, 0 to 11825
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   provincia       11826 non-null  object
 1   zona            11826 non-null  object
 2   titulo          11826 non-null  object
 3   PrecioActual    11826 non-null  int64
 4   PrecioAnterior  11826 non-null  int64
 5   metros          11826 non-null  int64
 6   habitaciones    11460 non-null  float64
 7   ascensor        11033 non-null  object
 8   localizacion    10730 non-null  object
 9   planta          10601 non-null  object
 10  baños           11826 non-null  int64
 11  tags            11664 non-null  object
 12  descripcion     11761 non-null  object
 13  Enlace          11826 non-null  object
dtypes: float64(1), int64(4), object(9)
memory usage: 1.3+ MB
None
Primeras filas
  provincia           zona                                             titulo  \
0    madrid  ciudad-lineal   Piso en calle de San Marcelo, 22, Ventas, Madrid
1    madrid    carabanchel  Piso en calle Cabo Nicolás Mur, San Isidro, Ma...
2    madrid         centro  Piso en calle de Rodas, Lavapiés-Embajadores, ...
3    madrid          usera  Piso en calle de Ferroviarios, Almendrales, Ma...
4    madrid         tetuan                    Dúplex en Bellas Vistas, Madrid

   PrecioActual  PrecioAnterior  metros  habitaciones ascensor localizacion  \
0        355000               0      69           2.0        S     EXTERIOR
1        149000          159000      91           3.0        N     EXTERIOR
2        195000               0      36           1.0        S          NaN
3        195000               0      58           1.0        S     INTERIOR
4        715000          750000     140           3.0        S     EXTERIOR

  planta  baños                                               tags  \
0     5ª      1  VIVIENDA,LUMINOSO,VISTAS,REFORMADA,PORTERO,EXT...
1     1ª      0            PISO,EXCLUSIVA,INMOBILIARIA,OPORTUNIDAD
2     2ª      0                                  EXCLUSIVA,ESTUDIO
3   BAJO      0                           VIVIENDA,HOGAR,FUNCIONAL
4     2ª      0                          TERRAZA,EXCLUSIVA,MODERNO

                                         descripcion  \
0  Particular Vende vivienda totalmente reformada...
1  Inmobiliarias Encuentro vende en exclusiva la ...
2  ESTUDIO EN PLENO CENTRO DE MADRIDSarago Servic...
3  Esta acogedora vivienda, ubicada en una planta...
4  Maravilloso ATICO de reciente construcción, co...

                                          Enlace
0  https://www.idealista.com/inmueble/106956987/
1  https://www.idealista.com/inmueble/106906044/
2  https://www.idealista.com/inmueble/107306175/
3  https://www.idealista.com/inmueble/106325171/
4  https://www.idealista.com/inmueble/106627265/
Describe()
                  count unique  \
provincia         11826      1
zona              11826     21
titulo            11826   5499
PrecioActual    11826.0    NaN
PrecioAnterior  11826.0    NaN
metros          11826.0    NaN
habitaciones    11460.0    NaN
ascensor          11033      2
localizacion      10730      2
planta            10601     27
baños           11826.0    NaN
tags              11664   8370
descripcion       11761  10924
Enlace            11826  11826

                                                              top   freq  \
provincia                                                  madrid  11826
zona                                          barrio-de-salamanca   2018
titulo                                       Piso en Goya, Madrid    203
PrecioActual                                                  NaN    NaN
PrecioAnterior                                                NaN    NaN
metros                                                        NaN    NaN
habitaciones                                                  NaN    NaN
ascensor                                                        S   8419
localizacion                                             EXTERIOR   9087
planta                                                         1ª   2108
baños                                                         NaN    NaN
tags                                             PISO,OPORTUNIDAD    158
descripcion     OBRA NUEVA DE VIVIENDAS TURÍSTICAS DE LUJO E I...     16
Enlace              https://www.idealista.com/inmueble/106956987/      1

                          mean             std      min       25%       50%  \
provincia                  NaN             NaN      NaN       NaN       NaN
zona                       NaN             NaN      NaN       NaN       NaN
titulo                     NaN             NaN      NaN       NaN       NaN
PrecioActual    1030501.460173  1237717.630328  12000.0  289000.0  620000.0
PrecioAnterior    73597.039151   363975.260549      0.0       0.0       0.0
metros              153.790039       766.21775     11.0      68.0     103.0
habitaciones          2.847731        1.432402      1.0       2.0       3.0
ascensor                   NaN             NaN      NaN       NaN       NaN
localizacion               NaN             NaN      NaN       NaN       NaN
planta                     NaN             NaN      NaN       NaN       NaN
baños                 0.394047        0.882134      0.0       0.0       0.0
tags                       NaN             NaN      NaN       NaN       NaN
descripcion                NaN             NaN      NaN       NaN       NaN
Enlace                     NaN             NaN      NaN       NaN       NaN

                      75%         max
provincia             NaN         NaN
zona                  NaN         NaN
titulo                NaN         NaN
PrecioActual    1329000.0  23000000.0
PrecioAnterior        0.0   8450000.0
metros              160.0     75000.0
habitaciones          3.0        20.0
ascensor              NaN         NaN
localizacion          NaN         NaN
planta                NaN         NaN
baños                 0.0         7.0
tags                  NaN         NaN
descripcion           NaN         NaN
Enlace                NaN         NaN
Nulos
habitaciones     366
ascensor         793
localizacion    1096
planta          1225
tags             162
descripcion       65
dtype: int64
Duplicados
0
Tamaño
Filas: 11826 | Columnas: 14

In [150]:
df_madrid.head()

,provincia,zona,titulo,PrecioActual,PrecioAnterior,metros,habitaciones,ascensor,localizacion,planta,baños,tags,descripcion,Enlace
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,0,69,2.0,S,EXTERIOR,5ª,1,"VIVIENDA,LUMINOSO,VISTAS,REFORMADA,PORTERO,EXT...",Particular Vende vivienda totalmente reformada...,https://www.idealista.com/inmueble/106956987/
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,159000,91,3.0,N,EXTERIOR,1ª,0,"PISO,EXCLUSIVA,INMOBILIARIA,OPORTUNIDAD",Inmobiliarias Encuentro vende en exclusiva la ...,https://www.idealista.com/inmueble/106906044/
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,0,36,1.0,S,NaN,2ª,0,"EXCLUSIVA,ESTUDIO",ESTUDIO EN PLENO CENTRO DE MADRIDSarago Servic...,https://www.idealista.com/inmueble/107306175/
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,0,58,1.0,S,INTERIOR,BAJO,0,"VIVIENDA,HOGAR,FUNCIONAL","Esta acogedora vivienda, ubicada en una planta...",https://www.idealista.com/inmueble/106325171/
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,750000,140,3.0,S,EXTERIOR,2ª,0,"TERRAZA,EXCLUSIVA,MODERNO","Maravilloso ATICO de reciente construcción, co...",https://www.idealista.com/inmueble/106627265/

### Unificamos títulos y eliminamos columnas con las que no vamos a trabajar

In [151]:
df_madrid.columns = df_madrid.columns.str.lower()
df_madrid = df_madrid.rename(columns ={'precioactual': 'precio_actual'})

In [152]:
columns_to_drop = { 
    'precioanterior',
    'localizacion',
    'tags',
    'descripcion',
    'enlace',
}
df_madrid = df_madrid.drop(columns=columns_to_drop)

In [153]:
## Comprobamos que funciona
df_madrid.head()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0

### Gestionamos los nulos

In [154]:
df_madrid.isnull().sum()

provincia           0
zona                0
titulo              0
precio_actual       0
metros              0
habitaciones      366
ascensor          793
planta           1225
baños               0
dtype: int64

In [155]:
## PARA UNIFICAR VALORES NULOS DE LA SERIE 'PLANTA' DECIDIMOS RELLENARLOS CON LA POSICIÓN DE ARRIBA. 
df_madrid['planta'].value_counts(dropna = False)

planta
1ª             2108
2ª             1779
3ª             1570
BAJO           1509
4ª             1266
NaN            1225
5ª              816
6ª              574
7ª              289
ENTREPLANTA     163
SÓTANO          128
8ª              124
9ª              106
10ª              47
11ª              35
12ª              22
-1               19
13ª              16
14ª               8
15ª               7
17ª               6
16ª               2
-2                2
20ª               1
27ª               1
22ª               1
21ª               1
18ª               1
Name: count, dtype: int64

In [156]:
df_madrid['planta'].fillna(method ='bfill', inplace= True)

/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_50171/3994935873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['planta'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_50171/3994935873.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['planta'].fillna(method ='bfill', inplace= True)

In [157]:
## Comprobamos que funciona
df_madrid['planta'].value_counts()

planta
1ª             2351
2ª             1977
3ª             1770
BAJO           1671
4ª             1416
5ª              910
6ª              643
7ª              321
ENTREPLANTA     182
SÓTANO          146
8ª              138
9ª              114
10ª              51
11ª              39
12ª              23
-1               22
13ª              18
14ª              10
15ª               7
17ª               7
16ª               2
-2                2
27ª               2
20ª               1
22ª               1
21ª               1
18ª               1
Name: count, dtype: int64

In [158]:
df_madrid['planta'].unique()

array(['5ª', '1ª', '2ª', 'BAJO', '3ª', '6ª', '4ª', '16ª', '13ª', '9ª',
       '7ª', '10ª', '8ª', '14ª', '11ª', '12ª', 'ENTREPLANTA', 'SÓTANO',
       '-1', '15ª', '17ª', '20ª', '-2', '27ª', '22ª', '21ª', '18ª'],
      dtype=object)

##### Hacemos lo mismo con las columnas de 'habitaciones' y 'ascensor'

In [159]:
df_madrid.isnull().sum()

provincia          0
zona               0
titulo             0
precio_actual      0
metros             0
habitaciones     366
ascensor         793
planta             0
baños              0
dtype: int64

In [160]:
df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
df_madrid['ascensor'].fillna(method ='bfill', inplace= True)

/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_50171/3544064126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_50171/3544064126.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_50171/3544064126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['ascensor'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_50171/3544064126.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['ascensor'].fillna(method ='bfill', inplace= True)

In [161]:
## Comprobamos que funciona
df_madrid['habitaciones'].value_counts()

habitaciones
3.0     3885
2.0     3485
1.0     1686
4.0     1537
5.0      713
6.0      297
7.0      109
8.0       49
9.0       27
10.0      15
11.0      10
13.0       3
16.0       3
15.0       3
12.0       2
20.0       1
17.0       1
Name: count, dtype: int64

In [162]:
## Comprobamos que funciona
df_madrid['ascensor'].value_counts()

ascensor
S    9015
N    2811
Name: count, dtype: int64

In [163]:
df_madrid.isnull().sum()

provincia        0
zona             0
titulo           0
precio_actual    0
metros           0
habitaciones     0
ascensor         0
planta           0
baños            0
dtype: int64

### Gestionamos los duplicados

In [164]:
df_madrid.duplicated(keep = 'first').sum()

np.int64(616)

In [165]:
df_madrid.duplicated().any()

np.True_

In [166]:
duplicados = df_madrid[df_madrid.duplicated(keep = False)].sort_values(by='precio_actual')

In [167]:
## Miramos cómo son nuetros duplicados
duplicados

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
10147,madrid,puente-de-vallecas,"Piso en calle Sierra de Alquife, 30, San Diego...",55500,41,1.0,N,3ª,0
11128,madrid,puente-de-vallecas,"Piso en calle Sierra de Alquife, 30, San Diego...",55500,41,1.0,N,3ª,0
1359,madrid,puente-de-vallecas,"Piso en San Diego, Madrid",75000,29,1.0,N,BAJO,0
5713,madrid,puente-de-vallecas,"Piso en San Diego, Madrid",75000,29,1.0,N,BAJO,0
11347,madrid,puente-de-vallecas,"Piso en calle del Doctor Bellido, San Diego, M...",75000,30,1.0,N,BAJO,0
...,...,...,...,...,...,...,...,...,...
8191,madrid,barrio-de-salamanca,"Piso en calle de José Ortega y Gasset, Castell...",7900000,473,4.0,S,2ª,0
10019,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",8900000,455,5.0,S,5ª,0
2312,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",8900000,455,5.0,S,5ª,0
7614,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",13000000,421,5.0,S,3ª,0
9675,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",13000000,421,5.0,S,3ª,0

In [168]:
## Eliminamos los duplicados 
df_madrid.drop_duplicates(inplace = True)

In [169]:
## Confirmamos el tamaño de nuesto fd 
df_madrid.shape

(11210, 9)

In [170]:
df_madrid['zona'].value_counts()

zona
barrio-de-salamanca    1792
centro                 1746
chamberi                758
chamartin               682
tetuan                  585
moncloa                 570
carabanchel             542
ciudad-lineal           527
puente-de-vallecas      511
retiro                  467
hortaleza               437
fuencarral              387
arganzuela              356
san-blas                333
latina                  321
villaverde              310
usera                   290
villa-de-vallecas       209
vicalvaro               193
moratalaz                97
barajas                  97
Name: count, dtype: int64

### Empezamos a tratar el df_madrid para unirlo a nuestro otro df

In [171]:
# Creamos una columna para hacer la traducción de las zonas de idealista a nivel distrito

zona_to_cod_distrito = {
    "centro": "01",
    "arganzuela": "02",
    "retiro": "03",
    "barrio-de-salamanca": "04",
    "chamartin": "05",
    "tetuan": "06",
    "chamberi": "07",
    "fuencarral": "08",
    "moncloa": "09",
    "latina": "10",
    "carabanchel": "11",
    "usera": "12",
    "puente-de-vallecas": "13",
    "moratalaz": "14",
    "ciudad-lineal": "15",
    "hortaleza": "16",
    "villaverde": "17",
    "villa-de-vallecas": "18",
    "vicalvaro": "19",
    "san-blas": "20",
    "barajas": "21",
}

df_madrid["cod_distrito"] = df_madrid["zona"].map(zona_to_cod_distrito)

df_madrid.head()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños,cod_distrito
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1,15
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0,11
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0,01
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0,12
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0,06

In [172]:
## Comprobamos que la columna de precio_actual se entienda como el tipo de ato que queremos: 
df_madrid.dtypes

provincia         object
zona              object
titulo            object
precio_actual      int64
metros             int64
habitaciones     float64
ascensor          object
planta            object
baños              int64
cod_distrito      object
dtype: object

## DF_RENTA

### Repetimos los procesos de exportación, exploración y limpieza con el otro df

In [173]:
## Importamos df
csv = '31097.csv'
df_renta = pd.read_csv(csv, sep = ';')

In [174]:
explorar_df(df_renta)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 6 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Municipios                            22 non-null     object
 1   Distritos                             21 non-null     object
 2   Secciones                             0 non-null      float64
 3   Indicadores de renta media y mediana  22 non-null     object
 4   Periodo                               22 non-null     int64
 5   Total                                 22 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 1.2+ KB
None
Primeras filas
     Municipios                   Distritos  Secciones  \
0  28079 Madrid                         NaN        NaN
1  28079 Madrid  2807901 Madrid distrito 01        NaN
2  28079 Madrid  2807902 Madrid distrito 02        NaN
3  28079 Madrid  2807903 Madrid distrito 03        NaN
4  28079 Madrid  2807904 Madrid distrito 04        NaN

  Indicadores de renta media y mediana  Periodo   Total
0           Renta neta media por hogar     2023  49.916
1           Renta neta media por hogar     2023  44.958
2           Renta neta media por hogar     2023  52.857
3           Renta neta media por hogar     2023  64.787
4           Renta neta media por hogar     2023  69.147
Describe()
                                     count unique                         top  \
Municipios                              22      1                28079 Madrid
Distritos                               21     21  2807901 Madrid distrito 01
Secciones                              0.0    NaN                         NaN
Indicadores de renta media y mediana    22      1  Renta neta media por hogar
Periodo                               22.0    NaN                         NaN
Total                                 22.0    NaN                         NaN

                                     freq       mean        std     min  \
Municipios                             22        NaN        NaN     NaN
Distritos                               1        NaN        NaN     NaN
Secciones                             NaN        NaN        NaN     NaN
Indicadores de renta media y mediana   22        NaN        NaN     NaN
Periodo                               NaN     2023.0        0.0  2023.0
Total                                 NaN  50.888091  13.572576  32.666

                                           25%      50%       75%     max
Municipios                                 NaN      NaN       NaN     NaN
Distritos                                  NaN      NaN       NaN     NaN
Secciones                                  NaN      NaN       NaN     NaN
Indicadores de renta media y mediana       NaN      NaN       NaN     NaN
Periodo                                 2023.0   2023.0    2023.0  2023.0
Total                                 40.58275  46.3495  62.15675  79.274
Nulos
Distritos     1
Secciones    22
dtype: int64
Duplicados
0
Tamaño
Filas: 22 | Columnas: 6

In [175]:
##Eliminamos columnas que no nos interesan 
columns_to_drop = { 
    'Municipios',
    'Secciones',
    'Indicadores de renta media y mediana',
    'Periodo',
}
df_renta = df_renta.drop(columns=columns_to_drop)

In [176]:
## Comprobamos los cambios
df_renta

                     Distritos   Total
0                          NaN  49.916
1   2807901 Madrid distrito 01  44.958
2   2807902 Madrid distrito 02  52.857
3   2807903 Madrid distrito 03  64.787
4   2807904 Madrid distrito 04  69.147
5   2807905 Madrid distrito 05  79.274
6   2807906 Madrid distrito 06  45.762
7   2807907 Madrid distrito 07  65.174
8   2807908 Madrid distrito 08  62.385
9   2807909 Madrid distrito 09  71.711
10  2807910 Madrid distrito 10  38.078
11  2807911 Madrid distrito 11  36.350
12  2807912 Madrid distrito 12  34.651
13  2807913 Madrid distrito 13  32.666
14  2807914 Madrid distrito 14  42.823
15  2807915 Madrid distrito 15  46.937
16  2807916 Madrid distrito 16  61.472
17  2807917 Madrid distrito 17  35.011
18  2807918 Madrid distrito 18  39.836
19  2807919 Madrid distrito 19  42.870
20  2807920 Madrid distrito 20  44.468
21  2807921 Madrid distrito 21  58.405

In [177]:
## Unificamos títulos de columnas 
df_renta = df_renta.rename(columns= {'Distritos':'cod_distrito', 'Total': 'renta_neta_media_por_hogar'})

In [178]:
## Comprobamos los cambios
df_renta

                  cod_distrito  renta_neta_media_por_hogar
0                          NaN                      49.916
1   2807901 Madrid distrito 01                      44.958
2   2807902 Madrid distrito 02                      52.857
3   2807903 Madrid distrito 03                      64.787
4   2807904 Madrid distrito 04                      69.147
5   2807905 Madrid distrito 05                      79.274
6   2807906 Madrid distrito 06                      45.762
7   2807907 Madrid distrito 07                      65.174
8   2807908 Madrid distrito 08                      62.385
9   2807909 Madrid distrito 09                      71.711
10  2807910 Madrid distrito 10                      38.078
11  2807911 Madrid distrito 11                      36.350
12  2807912 Madrid distrito 12                      34.651
13  2807913 Madrid distrito 13                      32.666
14  2807914 Madrid distrito 14                      42.823
15  2807915 Madrid distrito 15                      46.937
16  2807916 Madrid distrito 16                      61.472
17  2807917 Madrid distrito 17                      35.011
18  2807918 Madrid distrito 18                      39.836
19  2807919 Madrid distrito 19                      42.870
20  2807920 Madrid distrito 20                      44.468
21  2807921 Madrid distrito 21                      58.405

In [179]:
## Comprobamos los tipos
df_renta.dtypes

cod_distrito                   object
renta_neta_media_por_hogar    float64
dtype: object

In [180]:
## Decidimos cambiar a string la columna renta_neta_media_por_hogar para eliminar la , y luego pasarlo a int para poder trabajar en ellos como enteros. 
df_renta['renta_neta_media_por_hogar'] = df_renta['renta_neta_media_por_hogar'].astype(str)

In [181]:
df_renta['renta_neta_media_por_hogar'] = df_renta['renta_neta_media_por_hogar'].apply(lambda x: x.replace('.',''))

In [182]:
df_renta['renta_neta_media_por_hogar'] = df_renta['renta_neta_media_por_hogar'].astype(int)

In [183]:
## Comprobamos los cambios
df_renta

                  cod_distrito  renta_neta_media_por_hogar
0                          NaN                       49916
1   2807901 Madrid distrito 01                       44958
2   2807902 Madrid distrito 02                       52857
3   2807903 Madrid distrito 03                       64787
4   2807904 Madrid distrito 04                       69147
5   2807905 Madrid distrito 05                       79274
6   2807906 Madrid distrito 06                       45762
7   2807907 Madrid distrito 07                       65174
8   2807908 Madrid distrito 08                       62385
9   2807909 Madrid distrito 09                       71711
10  2807910 Madrid distrito 10                       38078
11  2807911 Madrid distrito 11                        3635
12  2807912 Madrid distrito 12                       34651
13  2807913 Madrid distrito 13                       32666
14  2807914 Madrid distrito 14                       42823
15  2807915 Madrid distrito 15                       46937
16  2807916 Madrid distrito 16                       61472
17  2807917 Madrid distrito 17                       35011
18  2807918 Madrid distrito 18                       39836
19  2807919 Madrid distrito 19                        4287
20  2807920 Madrid distrito 20                       44468
21  2807921 Madrid distrito 21                       58405

#### Decidimos quedarnos solo con los números de código de distrito

In [184]:
df_renta['cod_distrito'] = df_renta['cod_distrito'].str[-2:]

In [185]:
## Comprobamos los cambios
df_renta

   cod_distrito  renta_neta_media_por_hogar
0           NaN                       49916
1            01                       44958
2            02                       52857
3            03                       64787
4            04                       69147
5            05                       79274
6            06                       45762
7            07                       65174
8            08                       62385
9            09                       71711
10           10                       38078
11           11                        3635
12           12                       34651
13           13                       32666
14           14                       42823
15           15                       46937
16           16                       61472
17           17                       35011
18           18                       39836
19           19                        4287
20           20                       44468
21           21                       58405

#### Decidimos eliminar la columna con el nulo

In [186]:
df_renta = df_renta.drop(0)

In [187]:
## Reseteamos el índice 
df_renta.reset_index

<bound method DataFrame.reset_index of    cod_distrito  renta_neta_media_por_hogar
1            01                       44958
2            02                       52857
3            03                       64787
4            04                       69147
5            05                       79274
6            06                       45762
7            07                       65174
8            08                       62385
9            09                       71711
10           10                       38078
11           11                        3635
12           12                       34651
13           13                       32666
14           14                       42823
15           15                       46937
16           16                       61472
17           17                       35011
18           18                       39836
19           19                        4287
20           20                       44468
21           21                       58405>

## DF FINAL CON MERGE

In [188]:
## Unimos con un merge en un único df
df_final = pd.merge(df_madrid,df_renta, on = 'cod_distrito', how= 'left').copy()

In [189]:
df_final.head(10)

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños,cod_distrito,renta_neta_media_por_hogar
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1,15,46937
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0,11,3635
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0,01,44958
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0,12,34651
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0,06,45762
5,madrid,arganzuela,"Piso en Mazarredo, 18, Imperial, Madrid",1257000,135,3.0,S,3ª,0,02,52857
6,madrid,barrio-de-salamanca,"Piso en calle de Núñez de Balboa, Recoletos, M...",830000,81,1.0,S,6ª,0,04,69147
7,madrid,puente-de-vallecas,"Piso en calle de Rodríguez Espinosa, s/n, Palo...",70000,43,1.0,N,1ª,0,13,32666
8,madrid,moncloa,Chalet adosado en calle de la Isla de Alegranz...,2150000,500,6.0,S,3ª,0,09,71711
9,madrid,chamberi,"Piso en Blanca de Navarra, 4, Almagro, Madrid",1847800,139,2.0,S,3ª,0,07,65174

In [190]:
## Lo exportamos como CSV
df_final.to_csv('df_final.csv', index=False)

## CONECTANDO CON MYSQL

In [191]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import getpass  # To get the password without showing the input
password = getpass.getpass()

In [192]:
bd = "Proyecto_Venta_Madrid"
connection_string = 'mysql+pymysql://root:' + password + '@localhost/'+bd
engine = create_engine(connection_string)
engine

Engine(mysql+pymysql://root:***@localhost/Proyecto_Venta_Madrid)

In [193]:
df_madrid.to_sql('tabla_madrid', con=engine, if_exists='replace', index=False)
df_renta.to_sql('tabla_renta', con=engine, if_exists='replace', index=False)

21