####

In [58]:
import pandas as pd

df_madrid = pd.read_csv('Datos.csv')
print(df_madrid.head())

  provincia           zona                                             titulo  \
0    madrid  ciudad-lineal   Piso en calle de San Marcelo, 22, Ventas, Madrid
1    madrid    carabanchel  Piso en calle Cabo Nicolás Mur, San Isidro, Ma...
2    madrid         centro  Piso en calle de Rodas, Lavapiés-Embajadores, ...
3    madrid          usera  Piso en calle de Ferroviarios, Almendrales, Ma...
4    madrid         tetuan                    Dúplex en Bellas Vistas, Madrid

   PrecioActual  PrecioAnterior  metros  habitaciones ascensor localizacion  \
0        355000               0      69           2.0        S     EXTERIOR
1        149000          159000      91           3.0        N     EXTERIOR
2        195000               0      36           1.0        S          NaN
3        195000               0      58           1.0        S     INTERIOR
4        715000          750000     140           3.0        S     EXTERIOR

  planta  baños                                               tags  \
0     5ª      1  VIVIENDA,LUMINOSO,VISTAS,REFORMADA,PORTERO,EXT...
1     1ª      0            PISO,EXCLUSIVA,INMOBILIARIA,OPORTUNIDAD
2     2ª      0                                  EXCLUSIVA,ESTUDIO
3   BAJO      0                           VIVIENDA,HOGAR,FUNCIONAL
4     2ª      0                          TERRAZA,EXCLUSIVA,MODERNO

                                         descripcion  \
0  Particular Vende vivienda totalmente reformada...
1  Inmobiliarias Encuentro vende en exclusiva la ...
2  ESTUDIO EN PLENO CENTRO DE MADRIDSarago Servic...
3  Esta acogedora vivienda, ubicada en una planta...
4  Maravilloso ATICO de reciente construcción, co...

                                          Enlace
0  https://www.idealista.com/inmueble/106956987/
1  https://www.idealista.com/inmueble/106906044/
2  https://www.idealista.com/inmueble/107306175/
3  https://www.idealista.com/inmueble/106325171/
4  https://www.idealista.com/inmueble/106627265/

In [59]:
df_madrid.shape

(11826, 14)

In [60]:
df_madrid.head()

,provincia,zona,titulo,PrecioActual,PrecioAnterior,metros,habitaciones,ascensor,localizacion,planta,baños,tags,descripcion,Enlace
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,0,69,2.0,S,EXTERIOR,5ª,1,"VIVIENDA,LUMINOSO,VISTAS,REFORMADA,PORTERO,EXT...",Particular Vende vivienda totalmente reformada...,https://www.idealista.com/inmueble/106956987/
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,159000,91,3.0,N,EXTERIOR,1ª,0,"PISO,EXCLUSIVA,INMOBILIARIA,OPORTUNIDAD",Inmobiliarias Encuentro vende en exclusiva la ...,https://www.idealista.com/inmueble/106906044/
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,0,36,1.0,S,NaN,2ª,0,"EXCLUSIVA,ESTUDIO",ESTUDIO EN PLENO CENTRO DE MADRIDSarago Servic...,https://www.idealista.com/inmueble/107306175/
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,0,58,1.0,S,INTERIOR,BAJO,0,"VIVIENDA,HOGAR,FUNCIONAL","Esta acogedora vivienda, ubicada en una planta...",https://www.idealista.com/inmueble/106325171/
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,750000,140,3.0,S,EXTERIOR,2ª,0,"TERRAZA,EXCLUSIVA,MODERNO","Maravilloso ATICO de reciente construcción, co...",https://www.idealista.com/inmueble/106627265/

In [61]:
df_madrid.columns = df_madrid.columns.str.lower()

In [62]:
df_madrid = df_madrid.rename(columns ={'precioactual': 'precio_actual'})

In [63]:
columns_to_drop = { 
    'precioanterior',
    'localizacion',
    'tags',
    'descripcion',
    'enlace',
}
df_madrid = df_madrid.drop(columns=columns_to_drop)

In [64]:
df_madrid.head()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0

In [65]:
df_madrid.isnull().sum()

provincia           0
zona                0
titulo              0
precio_actual       0
metros              0
habitaciones      366
ascensor          793
planta           1225
baños               0
dtype: int64

In [66]:
## PARA UNIFICAR VALORES NULOS DE LA SERIE 'PLANTA' DECIIDIMOS RELLENARLOS CON LA POSICIÓN DE ARRIBA. 
df_madrid['planta'].value_counts(dropna = False)

planta
1ª             2108
2ª             1779
3ª             1570
BAJO           1509
4ª             1266
NaN            1225
5ª              816
6ª              574
7ª              289
ENTREPLANTA     163
SÓTANO          128
8ª              124
9ª              106
10ª              47
11ª              35
12ª              22
-1               19
13ª              16
14ª               8
15ª               7
17ª               6
16ª               2
-2                2
20ª               1
27ª               1
22ª               1
21ª               1
18ª               1
Name: count, dtype: int64

In [67]:
df_madrid['planta'].fillna(method ='bfill', inplace= True)

/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_41056/3994935873.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['planta'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_41056/3994935873.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['planta'].fillna(method ='bfill', inplace= True)

In [68]:
df_madrid['planta'].value_counts()

planta
1ª             2351
2ª             1977
3ª             1770
BAJO           1671
4ª             1416
5ª              910
6ª              643
7ª              321
ENTREPLANTA     182
SÓTANO          146
8ª              138
9ª              114
10ª              51
11ª              39
12ª              23
-1               22
13ª              18
14ª              10
15ª               7
17ª               7
16ª               2
-2                2
27ª               2
20ª               1
22ª               1
21ª               1
18ª               1
Name: count, dtype: int64

In [69]:
df_madrid['planta'].unique()

array(['5ª', '1ª', '2ª', 'BAJO', '3ª', '6ª', '4ª', '16ª', '13ª', '9ª',
       '7ª', '10ª', '8ª', '14ª', '11ª', '12ª', 'ENTREPLANTA', 'SÓTANO',
       '-1', '15ª', '17ª', '20ª', '-2', '27ª', '22ª', '21ª', '18ª'],
      dtype=object)

In [70]:
df_madrid.isnull().sum()

provincia          0
zona               0
titulo             0
precio_actual      0
metros             0
habitaciones     366
ascensor         793
planta             0
baños              0
dtype: int64

In [71]:
df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
df_madrid['ascensor'].fillna(method ='bfill', inplace= True)

/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_41056/3544064126.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_41056/3544064126.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['habitaciones'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_41056/3544064126.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_madrid['ascensor'].fillna(method ='bfill', inplace= True)
/var/folders/bk/hzstscb16rn4p883jsg8t31c0000gn/T/ipykernel_41056/3544064126.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_madrid['ascensor'].fillna(method ='bfill', inplace= True)

In [72]:
df_madrid['habitaciones'].value_counts()

habitaciones
3.0     3885
2.0     3485
1.0     1686
4.0     1537
5.0      713
6.0      297
7.0      109
8.0       49
9.0       27
10.0      15
11.0      10
13.0       3
16.0       3
15.0       3
12.0       2
20.0       1
17.0       1
Name: count, dtype: int64

In [73]:
df_madrid['ascensor'].value_counts()

ascensor
S    9015
N    2811
Name: count, dtype: int64

In [74]:
df_madrid.isnull().sum()

provincia        0
zona             0
titulo           0
precio_actual    0
metros           0
habitaciones     0
ascensor         0
planta           0
baños            0
dtype: int64

In [75]:
df_madrid.duplicated(keep = 'first').sum()

np.int64(616)

In [76]:
df_madrid.duplicated().any()

np.True_

In [77]:
duplicados = df_madrid[df_madrid.duplicated(keep = False)].sort_values(by='precio_actual')

In [78]:
duplicados

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
10147,madrid,puente-de-vallecas,"Piso en calle Sierra de Alquife, 30, San Diego...",55500,41,1.0,N,3ª,0
11128,madrid,puente-de-vallecas,"Piso en calle Sierra de Alquife, 30, San Diego...",55500,41,1.0,N,3ª,0
1359,madrid,puente-de-vallecas,"Piso en San Diego, Madrid",75000,29,1.0,N,BAJO,0
5713,madrid,puente-de-vallecas,"Piso en San Diego, Madrid",75000,29,1.0,N,BAJO,0
11347,madrid,puente-de-vallecas,"Piso en calle del Doctor Bellido, San Diego, M...",75000,30,1.0,N,BAJO,0
...,...,...,...,...,...,...,...,...,...
8191,madrid,barrio-de-salamanca,"Piso en calle de José Ortega y Gasset, Castell...",7900000,473,4.0,S,2ª,0
10019,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",8900000,455,5.0,S,5ª,0
2312,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",8900000,455,5.0,S,5ª,0
7614,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",13000000,421,5.0,S,3ª,0
9675,madrid,barrio-de-salamanca,"Piso en Recoletos, Madrid",13000000,421,5.0,S,3ª,0

In [79]:
df_madrid.drop_duplicates()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0
...,...,...,...,...,...,...,...,...,...
11821,madrid,centro,"Piso en calle del Amparo, Lavapiés-Embajadores...",189000,36,2.0,N,BAJO,0
11822,madrid,centro,"Piso en calle Gran Vía, Chueca-Justicia, Madrid",2600000,245,2.0,S,2ª,0
11823,madrid,tetuan,"Piso en calle del Capitán Blanco Argibay, Vald...",219000,56,1.0,S,BAJO,0
11824,madrid,carabanchel,"Piso en calle de Aceuchal, Vista Alegre, Madrid",165000,74,3.0,N,2ª,0
11825,madrid,san-blas,"Piso en calle de los Hermanos García Noblejas,...",178000,54,2.0,S,BAJO,0

In [80]:
df_madrid.shape

(11826, 9)

In [81]:
df_madrid['zona'].value_counts()

zona
barrio-de-salamanca    2018
centro                 1890
chamberi                796
chamartin               706
tetuan                  596
moncloa                 580
carabanchel             567
ciudad-lineal           537
puente-de-vallecas      526
retiro                  508
hortaleza               444
fuencarral              391
arganzuela              386
san-blas                335
latina                  331
villaverde              314
usera                   302
villa-de-vallecas       212
vicalvaro               193
moratalaz                97
barajas                  97
Name: count, dtype: int64

In [82]:
# Creamos una columna para hacer la traducción de las zonas de idealista
# a nivel distrito

zona_to_cod_distrito = {
    "centro": "01",
    "arganzuela": "02",
    "retiro": "03",
    "barrio-de-salamanca": "04",
    "chamartin": "05",
    "tetuan": "06",
    "chamberi": "07",
    "fuencarral": "08",
    "moncloa": "09",
    "latina": "10",
    "carabanchel": "11",
    "usera": "12",
    "puente-de-vallecas": "13",
    "moratalaz": "14",
    "ciudad-lineal": "15",
    "hortaleza": "16",
    "villaverde": "17",
    "villa-de-vallecas": "18",
    "vicalvaro": "19",
    "san-blas": "20",
    "barajas": "21",
}

df_madrid["cod_distrito"] = df_madrid["zona"].map(zona_to_cod_distrito)

df_madrid.head()

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños,cod_distrito
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1,15
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0,11
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0,01
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0,12
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0,06

In [83]:
df_madrid.dtypes

provincia         object
zona              object
titulo            object
precio_actual      int64
metros             int64
habitaciones     float64
ascensor          object
planta            object
baños              int64
cod_distrito      object
dtype: object

In [84]:
csv = '31097.csv'
df_renta = pd.read_csv(csv, sep = ';')

In [85]:
df_renta

,Municipios,Distritos,Secciones,Indicadores de renta media y mediana,Periodo,Total
0,28079 Madrid,NaN,NaN,Renta neta media por hogar,2023,49.916
1,28079 Madrid,2807901 Madrid distrito 01,NaN,Renta neta media por hogar,2023,44.958
2,28079 Madrid,2807902 Madrid distrito 02,NaN,Renta neta media por hogar,2023,52.857
3,28079 Madrid,2807903 Madrid distrito 03,NaN,Renta neta media por hogar,2023,64.787
4,28079 Madrid,2807904 Madrid distrito 04,NaN,Renta neta media por hogar,2023,69.147
5,28079 Madrid,2807905 Madrid distrito 05,NaN,Renta neta media por hogar,2023,79.274
6,28079 Madrid,2807906 Madrid distrito 06,NaN,Renta neta media por hogar,2023,45.762
7,28079 Madrid,2807907 Madrid distrito 07,NaN,Renta neta media por hogar,2023,65.174
8,28079 Madrid,2807908 Madrid distrito 08,NaN,Renta neta media por hogar,2023,62.385
9,28079 Madrid,2807909 Madrid distrito 09,NaN,Renta neta media por hogar,2023,71.711
10,28079 Madrid,2807910 Madrid distrito 10,NaN,Renta neta media por hogar,2023,38.078
11,28079 Madrid,2807911 Madrid distrito 11,NaN,Renta neta media por hogar,2023,36.350
12,28079 Madrid,2807912 Madrid distrito 12,NaN,Renta neta media por hogar,2023,34.651
13,28079 Madrid,2807913 Madrid distrito 13,NaN,Renta neta media por hogar,2023,32.666
14,28079 Madrid,2807914 Madrid distrito 14,NaN,Renta neta media por hogar,2023,42.823
15,28079 Madrid,2807915 Madrid distrito 15,NaN,Renta neta media por hogar,2023,46.937
16,28079 Madrid,2807916 Madrid distrito 16,NaN,Renta neta media por hogar,2023,61.472
17,28079 Madrid,2807917 Madrid distrito 17,NaN,Renta neta media por hogar,2023,35.011
18,28079 Madrid,2807918 Madrid distrito 18,NaN,Renta neta media por hogar,2023,39.836
19,28079 Madrid,2807919 Madrid distrito 19,NaN,Renta neta media por hogar,2023,42.870
20,28079 Madrid,2807920 Madrid distrito 20,NaN,Renta neta media por hogar,2023,44.468
21,28079 Madrid,2807921 Madrid distrito 21,NaN,Renta neta media por hogar,2023,58.405

In [86]:
columns_to_drop = { 
    'Municipios',
    'Secciones',
    'Indicadores de renta media y mediana',
    'Periodo',
}
df_renta = df_renta.drop(columns=columns_to_drop)

In [87]:
df_renta

                     Distritos   Total
0                          NaN  49.916
1   2807901 Madrid distrito 01  44.958
2   2807902 Madrid distrito 02  52.857
3   2807903 Madrid distrito 03  64.787
4   2807904 Madrid distrito 04  69.147
5   2807905 Madrid distrito 05  79.274
6   2807906 Madrid distrito 06  45.762
7   2807907 Madrid distrito 07  65.174
8   2807908 Madrid distrito 08  62.385
9   2807909 Madrid distrito 09  71.711
10  2807910 Madrid distrito 10  38.078
11  2807911 Madrid distrito 11  36.350
12  2807912 Madrid distrito 12  34.651
13  2807913 Madrid distrito 13  32.666
14  2807914 Madrid distrito 14  42.823
15  2807915 Madrid distrito 15  46.937
16  2807916 Madrid distrito 16  61.472
17  2807917 Madrid distrito 17  35.011
18  2807918 Madrid distrito 18  39.836
19  2807919 Madrid distrito 19  42.870
20  2807920 Madrid distrito 20  44.468
21  2807921 Madrid distrito 21  58.405

In [88]:
df_renta = df_renta.rename(columns= {'Distritos':'cod_distrito', 'Total': 'renta_neta_media_por_hogar'})

In [89]:
df_renta

                  cod_distrito  renta_neta_media_por_hogar
0                          NaN                      49.916
1   2807901 Madrid distrito 01                      44.958
2   2807902 Madrid distrito 02                      52.857
3   2807903 Madrid distrito 03                      64.787
4   2807904 Madrid distrito 04                      69.147
5   2807905 Madrid distrito 05                      79.274
6   2807906 Madrid distrito 06                      45.762
7   2807907 Madrid distrito 07                      65.174
8   2807908 Madrid distrito 08                      62.385
9   2807909 Madrid distrito 09                      71.711
10  2807910 Madrid distrito 10                      38.078
11  2807911 Madrid distrito 11                      36.350
12  2807912 Madrid distrito 12                      34.651
13  2807913 Madrid distrito 13                      32.666
14  2807914 Madrid distrito 14                      42.823
15  2807915 Madrid distrito 15                      46.937
16  2807916 Madrid distrito 16                      61.472
17  2807917 Madrid distrito 17                      35.011
18  2807918 Madrid distrito 18                      39.836
19  2807919 Madrid distrito 19                      42.870
20  2807920 Madrid distrito 20                      44.468
21  2807921 Madrid distrito 21                      58.405

In [90]:
df_renta

                  cod_distrito  renta_neta_media_por_hogar
0                          NaN                      49.916
1   2807901 Madrid distrito 01                      44.958
2   2807902 Madrid distrito 02                      52.857
3   2807903 Madrid distrito 03                      64.787
4   2807904 Madrid distrito 04                      69.147
5   2807905 Madrid distrito 05                      79.274
6   2807906 Madrid distrito 06                      45.762
7   2807907 Madrid distrito 07                      65.174
8   2807908 Madrid distrito 08                      62.385
9   2807909 Madrid distrito 09                      71.711
10  2807910 Madrid distrito 10                      38.078
11  2807911 Madrid distrito 11                      36.350
12  2807912 Madrid distrito 12                      34.651
13  2807913 Madrid distrito 13                      32.666
14  2807914 Madrid distrito 14                      42.823
15  2807915 Madrid distrito 15                      46.937
16  2807916 Madrid distrito 16                      61.472
17  2807917 Madrid distrito 17                      35.011
18  2807918 Madrid distrito 18                      39.836
19  2807919 Madrid distrito 19                      42.870
20  2807920 Madrid distrito 20                      44.468
21  2807921 Madrid distrito 21                      58.405

In [91]:
df_renta['cod_distrito'] = df_renta['cod_distrito'].str[-2:]

In [92]:
df_renta

   cod_distrito  renta_neta_media_por_hogar
0           NaN                      49.916
1            01                      44.958
2            02                      52.857
3            03                      64.787
4            04                      69.147
5            05                      79.274
6            06                      45.762
7            07                      65.174
8            08                      62.385
9            09                      71.711
10           10                      38.078
11           11                      36.350
12           12                      34.651
13           13                      32.666
14           14                      42.823
15           15                      46.937
16           16                      61.472
17           17                      35.011
18           18                      39.836
19           19                      42.870
20           20                      44.468
21           21                      58.405

In [93]:
df_renta = df_renta.drop(0)

In [94]:
df_renta.reset_index

<bound method DataFrame.reset_index of    cod_distrito  renta_neta_media_por_hogar
1            01                      44.958
2            02                      52.857
3            03                      64.787
4            04                      69.147
5            05                      79.274
6            06                      45.762
7            07                      65.174
8            08                      62.385
9            09                      71.711
10           10                      38.078
11           11                      36.350
12           12                      34.651
13           13                      32.666
14           14                      42.823
15           15                      46.937
16           16                      61.472
17           17                      35.011
18           18                      39.836
19           19                      42.870
20           20                      44.468
21           21                      58.405>

##### DF FINAL CON MERGE

In [95]:
df_final = pd.merge(df_madrid,df_renta, on = 'cod_distrito', how= 'left').copy()

In [96]:
df_final.head(10)

,provincia,zona,titulo,precio_actual,metros,habitaciones,ascensor,planta,baños,cod_distrito,renta_neta_media_por_hogar
0,madrid,ciudad-lineal,"Piso en calle de San Marcelo, 22, Ventas, Madrid",355000,69,2.0,S,5ª,1,15,46.937
1,madrid,carabanchel,"Piso en calle Cabo Nicolás Mur, San Isidro, Ma...",149000,91,3.0,N,1ª,0,11,36.350
2,madrid,centro,"Piso en calle de Rodas, Lavapiés-Embajadores, ...",195000,36,1.0,S,2ª,0,01,44.958
3,madrid,usera,"Piso en calle de Ferroviarios, Almendrales, Ma...",195000,58,1.0,S,BAJO,0,12,34.651
4,madrid,tetuan,"Dúplex en Bellas Vistas, Madrid",715000,140,3.0,S,2ª,0,06,45.762
5,madrid,arganzuela,"Piso en Mazarredo, 18, Imperial, Madrid",1257000,135,3.0,S,3ª,0,02,52.857
6,madrid,barrio-de-salamanca,"Piso en calle de Núñez de Balboa, Recoletos, M...",830000,81,1.0,S,6ª,0,04,69.147
7,madrid,puente-de-vallecas,"Piso en calle de Rodríguez Espinosa, s/n, Palo...",70000,43,1.0,N,1ª,0,13,32.666
8,madrid,moncloa,Chalet adosado en calle de la Isla de Alegranz...,2150000,500,6.0,S,3ª,0,09,71.711
9,madrid,chamberi,"Piso en Blanca de Navarra, 4, Almagro, Madrid",1847800,139,2.0,S,3ª,0,07,65.174

In [97]:
df_final.to_csv('df_final.csv', index=False)

In [98]:
df_renta.dtypes

cod_distrito                   object
renta_neta_media_por_hogar    float64
dtype: object

In [99]:
df_renta['renta_neta_media_por_hogar'] = df_renta['renta_neta_media_por_hogar'].astype(str)

In [100]:
df_renta.dtypes

cod_distrito                  object
renta_neta_media_por_hogar    object
dtype: object

In [101]:
df_renta['renta_neta_media_por_hogar'] = df_renta['renta_neta_media_por_hogar'].apply(lambda x: x.replace('.',''))

In [102]:
df_renta

   cod_distrito renta_neta_media_por_hogar
1            01                      44958
2            02                      52857
3            03                      64787
4            04                      69147
5            05                      79274
6            06                      45762
7            07                      65174
8            08                      62385
9            09                      71711
10           10                      38078
11           11                       3635
12           12                      34651
13           13                      32666
14           14                      42823
15           15                      46937
16           16                      61472
17           17                      35011
18           18                      39836
19           19                       4287
20           20                      44468
21           21                      58405

In [103]:
df_renta['renta_neta_media_por_hogar'] = df_renta['renta_neta_media_por_hogar'].astype(int)

##### CONECTANDO CON MYSQL

In [104]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import getpass  # To get the password without showing the input
password = getpass.getpass()

In [105]:
bd = "Proyecto_Venta_Madrid"
connection_string = 'mysql+pymysql://root:' + password + '@localhost/'+bd
engine = create_engine(connection_string)
engine

Engine(mysql+pymysql://root:***@localhost/Proyecto_Venta_Madrid)

In [106]:
df_madrid.to_sql('tabla_madrid', con=engine, if_exists='replace', index=False)
df_renta.to_sql('tabla_renta', con=engine, if_exists='replace', index=False)

21